---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- include_tasks: basic-selinux.yml
  when: dotfiles__install_python_selinux | bool

- include_tasks: bashrc.yml
  when: base__modify_bashrc | bool

- name: Copy vimrc configuration to root
  become: yes
  copy:
    src: 'templates/vimrc'
    dest: '/root/.vimrc'
    owner: root
    group: root
    mode: 'u=rw,g=r,o='

- name: Copy vimrc configuration to non admin users
  become: yes
  copy:
    src: 'templates/vimrc'
    dest: '/home/{{ item }}/.vimrc'
    owner: '{{ item }}'
    group: '{{ item }}'
    mode: 'u=rw,g=r,o='
  with_items: "{{ accounts }}"
  when:
    - accounts is defined
    - accounts != ['root']
    - accounts != 'root'

- name: create .config/ranger/ directory
  become: true
  file:
    path: "/home/{{ item }}/.config/ranger"
    state: directory
    recurse: yes
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  with_items: "{{ accounts }}"
  when:
    - base__ranger_hidden_files | bool
    - accounts is defined
    - accounts != ['root']
    - accounts != 'root'

- name: create .config/ranger/rc.conf file
  become: true
  template:
    src: templates/ranger_rc.conf.j2
    dest: "/home/{{ item }}/.config/ranger/rc.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  with_items: "{{ accounts }}"
  when:
    - base__ranger_hidden_files | bool
    - accounts is defined
    - accounts != ['root']
    - accounts != 'root'
